name: Testing on devices

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            node-version: 10
          - os: ubuntu-latest
            node-version: 12
          - os: ubuntu-latest
            node-version: 14
          - os: ubuntu-latest
            node-version: lts/*

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.2.0
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm i
    - name: Test in node
      run: npm test
